#include "./pkmn.h"
const PkmnMove ALL_POKEMON_MOVES[MOVE_ID_COUNT] = {
    {
        .name = "Tackle",
        .type = PKMN_TYPE_NORMAL,
        .category = PHYSICAL_MOVE_CATEGORY,
        .power = 35,
        .accuracy = 95,
        .pp = 35,
        .remainingPp = 35,
        .description = "A standard physical attack.",
        .effectChance = 0,
        .negativeEffect = PKMN_STATUS_NONE,
        .requiresRest = false,
        .requiresLoad = false,
    },
    {
        .name = "Flamethrower",
        .type = PKMN_TYPE_FIRE,
        .category = SPECIAL_MOVE_CATEGORY,
        .power = 90,
        .accuracy = 100,
        .pp = 15,
        .remainingPp = 15,
        .description = "May cause a burn.",
        .effectChance = 10,
        .negativeEffect = PKMN_STATUS_BURN,
        .requiresRest = false,
        .requiresLoad = false,
    },
    {
        .name = "Surf",
        .type = PKMN_TYPE_WATER,
        .category = SPECIAL_MOVE_CATEGORY,
        .power = 90,
        .accuracy = 100,
        .pp = 15,
        .remainingPp = 15,
        .description = "Strikes all adjacent Pokémon.",
        .effectChance = 0,
        .negativeEffect = PKMN_STATUS_NONE,
        .requiresRest = false,
        .requiresLoad = false,
    },
    {
        .name = "Thunder Wave",
        .type = PKMN_TYPE_ELECTRIC,
        .category = STATUS_MOVE_CATEGORY,
        .power = 0,
        .accuracy = 90,
        .pp = 20,
        .remainingPp = 20,
        .description = "Paralyzes the target.",
        .effectChance = 0,
        .negativeEffect = PKMN_STATUS_PARALYSIS,
        .requiresRest = false,
        .requiresLoad = false,
    },
    {
        .name = "Stone Edge",
        .type = PKMN_TYPE_ROCK,
        .category = PHYSICAL_MOVE_CATEGORY,
        .power = 100,
        .accuracy = 80,
        .pp = 5,
        .remainingPp = 5,
        .description = "High critical-hit ratio.",
        .effectChance = 0,
        .negativeEffect = PKMN_STATUS_NONE,
        .requiresRest = false,
        .requiresLoad = false,
    },
    {
        .name = "Roost",
        .type = PKMN_TYPE_FLYING,
        .category = STATUS_MOVE_CATEGORY,
        .power = 0,
        .accuracy = 100,
        .pp = 10,
        .remainingPp = 10,
        .description = "Heals 50% max HP.",
        .effectChance = 0,
        .negativeEffect = PKMN_STATUS_NONE,
        .requiresRest = false,
        .requiresLoad = false,
    },
    {
        .name = "Hyper Beam",
        .type = PKMN_TYPE_NORMAL,
        .category = SPECIAL_MOVE_CATEGORY,
        .power = 150,
        .accuracy = 90,
        .pp = 5,
        .remainingPp = 5,
        .description = "User must rest next turn.",
        .effectChance = 0,
        .negativeEffect = PKMN_STATUS_NONE,
        .requiresRest = true,
        .requiresLoad = false,
    },
    {
        .name = "Fly",
        .type = PKMN_TYPE_FLYING,
        .category = PHYSICAL_MOVE_CATEGORY,
        .power = 90,
        .accuracy = 95,
        .pp = 15,
        .remainingPp = 15,
        .description = "Flies high, strikes next turn.",
        .effectChance = 0,
        .negativeEffect = PKMN_STATUS_NONE,
        .requiresRest = false,
        .requiresLoad = true,
    },
    {
        .name = "Close Combat",
        .type = PKMN_TYPE_FIGHTING,
        .category = PHYSICAL_MOVE_CATEGORY,
        .power = 120,
        .accuracy = 100,
        .pp = 5,
        .remainingPp = 5,
        .description = "Lowers Defense/SpDef.",
        .effectChance = 0,
        .negativeEffect = PKMN_STATUS_NONE,
        .requiresRest = false,
        .requiresLoad = false,
    },
    {
        .name = "Aura Sphere",
        .type = PKMN_TYPE_FIGHTING,
        .category = SPECIAL_MOVE_CATEGORY,
        .power = 80,
        .accuracy = 100,
        .pp = 20,
        .remainingPp = 20,
        .description = "Never misses the target.",
        .effectChance = 0,
        .negativeEffect = PKMN_STATUS_NONE,
        .requiresRest = false,
        .requiresLoad = false,
    },
    {
        .name = "Will-O-Wisp",
        .type = PKMN_TYPE_FIRE,
        .category = STATUS_MOVE_CATEGORY,
        .power = 0,
        .accuracy = 85,
        .pp = 15,
        .remainingPp = 15,
        .description = "Inflicts a burn.",
        .effectChance = 0,
        .negativeEffect = PKMN_STATUS_BURN,
        .requiresRest = false,
        .requiresLoad = false,
    },
    {
        .name = "Ice Beam",
        .type = PKMN_TYPE_ICE,
        .category = SPECIAL_MOVE_CATEGORY,
        .power = 90,
        .accuracy = 100,
        .pp = 10,
        .remainingPp = 10,
        .description = "May freeze the target.",
        .effectChance = 10,
        .negativeEffect = PKMN_STATUS_FREEZE,
        .requiresRest = false,
        .requiresLoad = false,
    }};
